services:
  - type: web
    name: 28hse-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000

